
export CODAR_CHEETAH_GROUP_WALLTIME="4800"
export CODAR_CHEETAH_GROUP_MAX_PROCS="6144"

export CODAR_CHEETAH_SCHEDULER_ACCOUNT="phy130"
# queue on PBS, partition on SLURM
export CODAR_CHEETAH_SCHEDULER_QUEUE=""
# SLURM specific options
export CODAR_CHEETAH_SCHEDULER_CONSTRAINT=""
export CODAR_CHEETAH_SCHEDULER_LICENSE=""

export CODAR_CHEETAH_CAMPAIGN_NAME="codar.cheetah.GTC"

export CODAR_CHEETAH_GROUP_NAME="gtc-bb-1"
export CODAR_CHEETAH_GROUP_NODES="512"
export CODAR_CHEETAH_GROUP_NODE_EXCLUSIVE="True"
export CODAR_CHEETAH_GROUP_PROCESSES_PER_NODE="42"
export CODAR_CHEETAH_MACHINE_NAME="summit"
