
export CODAR_CHEETAH_GROUP_WALLTIME="3000"
export CODAR_CHEETAH_GROUP_MAX_PROCS="21600"

export CODAR_CHEETAH_SCHEDULER_ACCOUNT="csc143"
# queue on PBS, partition on SLURM
export CODAR_CHEETAH_SCHEDULER_QUEUE=""
# SLURM specific options
export CODAR_CHEETAH_SCHEDULER_CONSTRAINT=""
export CODAR_CHEETAH_SCHEDULER_LICENSE=""

export CODAR_CHEETAH_CAMPAIGN_NAME="codar.cheetah.SpecFEM3D_Globe"

export CODAR_CHEETAH_GROUP_NAME="256-50-6GBpn-flush-continous-1sec-all-2ppn"
export CODAR_CHEETAH_GROUP_NODES="800"
export CODAR_CHEETAH_GROUP_NODE_EXCLUSIVE="True"
export CODAR_CHEETAH_GROUP_PROCESSES_PER_NODE="42"
export CODAR_CHEETAH_MACHINE_NAME="summit"
